#set math.equation(numbering: "(1)")
#set page(margin: (x: 1cm, y: 1cm))
#import "@preview/physica:0.9.5": *
#place(top + right, rect(inset: 3pt)[Math541|HW2])

= P1
#align(
  left,
  rect(inset: 12pt)[Determine the order of each of the elements of the dihedral group $D_8.$ ]
)
Since $ 
    D_8 &= angle.l r, s bar r^4 = s^2  = e, r s = s r^(-1) angle.r \ 
    & = {e , r, r^2, r^3, s, r s, r^2 s, r^3 s}.
$ 
Using 
$ 
   | r^k | = n/(gcd(n, k)) = 4/(gcd(4, k)), 
$ 
and the fact that any reflection $r^k s$ is of order 2, since  $ 
     (r^(k) s)^2 = r^k s r^k s = r^k r^(-k) s^2 = e, 
$ 
we have: $ 
    |e| = 1, \ 
    |r| = 4, med |r^2 | = 2, med |r^3| = 4, \ 
    |s| = | r s | = | r^2 s | = | r^3 s | = 2. 
$ 

#pagebreak()
= P2 
#align(
  left,
  rect(inset: 12pt)[Suppose for some $n >= 3 $ that $z in D_(2n) $is a non-identity element s.t. $z g = g z$ for all $g in D_(2n).$ Prove that $n$ is even ( $n = 2k$ ), and $z = r^(k) $ where r is order-n generator of $D_(2n.)$    
  ]
)

Any element in $D_(2n)$ is either a rotation $r^a$ or a reflection $r^a s$ for some integer $a.$

- Suppose $z = r^(a) s$ is a reflection, m$z r = r z.$ Then, $ 
    z r &= ( r^(a) s)r = r^(a-1 ) r s r = r^(a - 1) s \ 
     r z & = r( r^(a) s) = r(r^(a-1) s r^(-1))=r^a s r^(-1)= r^(a+1) s.  
$ 
To have $z r = r z,$ we must have $r^(a-1) s = r^(a+1) s,$ which implies $r^2 = e.$ This contradicts the assumption that $n >= 3.$ Thus, $z$ must be a rotation.

- Now, consider $ a in {1, 2, dots, n-1}, z= r^a eq.not e.$ 
Commutativity gives $ 
    z r = r z => r^(a+1) = r^(a+1) , "tautology." \
    s z = z s => s r^a = r^a s = r^(-a)s 
$ 
$ 
    => r^a s = r^(-a) s \ => r^a = r^(-a) \ => r^(2a) = e. 
$ 
Since the order of $r$ is $n,$ we must have $n | 2a => 0 < 2a <2n$.
Since $z = r^a eq.not e,$ n does not divide a.

Thus, the only possibility is $2a = n.$ Writing $n = 2k$, we have $a = k$ and $z = r^k.$ #h(1fr) $qed$

#pagebreak()
= P3
=== a. Prove that every element of $D_(2n)$ which is not a power of r has order 2.

As proved in P1: For any reflection $r^k s$,
$ 
    (r^(k) s)^2 = r^k s r^k s = r^k r^(-k) s^2 = e.
$ 

=== b.Deduce that $D_(2n)$ is generated by $s, s r $ , both of which have order 2.

Consider $(s r )^2 = s r s r = s s r^(-1) r = s s = e,$ and $s^2 = e$. Thus, both $s$ and $s r$ are of order 2.

Since $r s = s r^(-1) => r = s(s r).$ \ Let $H = angle.l s, s r angle.r  $, then $r = s(s r) in H, s in H.$ Thus $H$ contains both generators of $D_(2n).$ But $angle.l r,s angle.r = D_(2n) => H subset.eq D_(2n). $ This implies $D_(2n) = H = angle.l s, s r  angle.r $. #h(1fr) $qed$   

=== c. Show $angle.l a, b bar a^2  = b^2  = (a b)^n = e angle.r $ gives a presentation for $D_(2n)$ in terms of the two generators $a = s, b = s r. $

First, let $a := s, b := s r.$ Then, using the definition for $s,r$ : $ 
    a^2 =s^2  = e; quad b^2 = (s r)^2 = s r s r = s s r^(-1) r = e; \ 
    (a b)^n = (s (s r))^n = r^n = e.
$ Thus the relation of $a ,b$ follows from that of $s, r.$

Conversely, let $s := a, r := a b.$ Then, using the definition for $a,b$ : $ 
    s^2 = a^2 = e; quad r^n = (a b)^n = e; $
    and since $a^2  = e => a^(-1) = a; b^2  = e => b^(-1) = b, and$ 
    $ 
    r s = (a b) a = a (b a) = a (a b)^(-1) = s r^(-1).
$ Thus the relation of $s ,r$ follows from that of $a,b.$
This shows the two presentations are equivalent. #h(1fr) $qed$
 

#pagebreak()
= P4
#align(
  left,
  rect(inset: 12pt)[Prove that the group of rigid motions of a regular tetrahedron in $R^3$ has order 12, and that the group of rigid motions of a regular octahedron in $R^3$ has order 24.
  ]
)
- A tetrahedron has 4 vertices, which we label form 1 to 4. 
  A rigid motion in G sents vertex 1 to four possible locations. Afterwhich, there are three possible locations for vertex 2, and then the location of the remaining two vertices are determined. Thus, by the multiplication principle, $|G| = 4 times 3 = 12.$

- An octahedron has 6 vertices, from which we label from 1 to 6. 
  A rigid motion in G sents vertex 1 to six possible locations. Afterwhich, there are four possible locations for vertex 2, and then the location of the remaining four vertices are determined. Thus, by the multiplication principle, $|G| = 6 times 4 = 24.$

#pagebreak()
= P5
#align(
  left,
  rect(inset: 12pt)[Prove that if $Omega = NN, $then the group $S_Omega$ is infinite.  ]
)


Let $Omega = {1,2,3, dots}$ and let $S_Omega $ be the group of all bijections $Omega -> Omega$ under composition.


For each $n >= 1, $ define $sigma_n in S_Omega$ by: 
- $sigma_n(2n-1) = 2n, quad sigma_n(2n) = 2n-1,$
- $sigma_n(k) = k forall k eq.not 2n-1, 2n.$
Thus $sigma_n$ is the transposition $(2n-1, 2n),$ hence a bijection, so $sigma_n in S_Omega$.


If $i eq.not j,$ then ${ 2i - 1, 2i}$ and ${ 2j - 1, 2j}$ are disjoint, and in particular: 
$ 
    sigma_i(2i - 1) = 2i eq. not 2i - 1 = sigma_j(2i - 1),
$
so $sigma_i eq.not sigma_j.$

Therefore the set ${ sigma_1, sigma_2, dots}$ gives infinitely many distinct elements of $S_Omega,$ and $S_Omega$ is infinite.

#pagebreak()
= P6
It is clear, by observation, that $ 
    sigma = (1med  13 med 5med 10) (3med 15med 8) (4med 14med 11med 7med 12med 9)\ 
tau = ( 1 med 14) (2 med 9 med 15 med 13 med 4) ( 3 med 10) (5 med 12 med 7) ( 8 med 11)
$ 
and so $ 
sigma tau=(1 med 11 med 3)(2 med 4)(5 med 9 med 8 med 7 10 med 15)(13 med 14)} \ 
tau sigma=(1 med 4)(2 med 9)(3 med 13 med 12 med 15 med 11 med 5)(8 med 10 med 14)} 
$ 

$ 
abs(sigma) = lcm(4,3,6) = 12; abs(tau) = lcm(2,5,2,3,2) = 30; \ 
abs(sigma tau) = lcm(3,2,6,2) = 6; abs(tau sigma) = lcm(2,2,6,3) = 6.
$ 

#pagebreak()
= P7
#align(
  left,
  rect(inset: 12pt)[Let $a$ be the 12-cycle (1 2 3 4 5 6 7 8 9 10 11 12). For which positive integers $i$ is $a^i$ also a 12-cycle? ]
)
Since $a$ is of order 12, $ abs(a^i) = frac(12 , gcd(12,i)). $ Then,  to enforce $abs(a^i) = 12,$ we need $gcd(12,i) = 1$, that is, $i in {1,  5, 7, 11}.$   

#pagebreak()
= P8
#align(
  left,
  rect(inset: 12pt)[Prove that if $a $ is the m-cycle $(a_1 med a_2 med dots a_m)$, then for all $i in {1, 2, dots, m}$ , $a^i (a_k) = a_(k+i)$, where $k+i$ is replaced by its least residue modulo $m$ when $k+i > m$. Deduce that $|a| = m.$    ]
)

1. Use induction to prove $a^i (a_k) = a_(k+1) forall i in {1, dots, m}. $
- Base case:  By definition, for $i = 1, $ $ 
    a(a_k) = cases(a_(k+1) quad 1<= k <= m-1, a_1 quad k = m).

$  exactly $a_(k+1)$ with indices modulo $m$.
- Inductive step: Suppose $a^i (a_k) = a_(k+i) forall k in {1, dots, m}.$ Then, for $i + 1,$ we have:
  $ 
      a^(i+1)(a_k) = a(a^i (a_k)) = a(a_(k+1)) = a_(a + i + 1).
  $ 
  again interpreting $k+i+1$ modulo $m$. This proves the formula for $i+1$, and by induction, for all $i in {1, dots, m}.$

2. Since for every $k, $ $ 
    a^m (a_k) = a_(k+m) = a_k,
$ 
we have $a^m = e.$

For $1 <= t <m, $ then $ 
    a^t(a_1) = a_(1+t) eq.not a_1 ,
$ 
so $a^t = e$. Therefore the least positive exponent sending $e$ to $e$ is $m,$ and $|a| = m.$ #h(1fr) $qed$ 
