#set math.equation(numbering: "(1)")
#set text(
font: "Palatino Linotype",size: 11pt)
#set page(margin: (x: 1cm, y: 1cm), numbering: "1/1")
#import "@preview/physica:0.9.6": *
#place(top + right, rect(inset: 3pt)[MATH 541 HW5 Harry Luo
])
= 1
#align(
  left,
  rect(inset: 8pt)[ For set A and group G, $A subset G$; prove: 
   $A = expectationvalue(A) $ iff $A <= G.$   ]
)
- $=>:$ Assume $A = expectationvalue(A) $ , then A is a subgroup of G by definition, as it is the intersection of all subgroups of G containing A. Thus, $A <= G.$
- $arrow.l.double:$ Assume A is a subgroup of G. Recall $ expval(A)= inter.big_(A subset.eq H \ H <= G ) H,
  $ so $A subset.eq H, med forall H<= G$ , so $A subset.eq expval(A).$ 

  Assume $a in expectationvalue(A) , $ then by definitiion, $a = a_1^(epsilon_1) a_2^(epsilon_2) dots a_k^(epsilon_k) in A,$ since A is closed under operations (a subgroud) ,and $a_i in A.$ Thus, $ expectationvalue(A) subset.eq A.$ 
  Therefore, $A = expectationvalue(A).$
Thus, $A = expectationvalue(A) "iff" A <= G.$
#h(1fr) $qed$
#pagebreak()

= 2 
#align(
  left,
  rect(inset: 8pt)[Prove that subgroup of $S_4$ generated by (1 2) and (1 3)(2 4) is isomorphic to $D_8.$]
)
$ 
H = angle.l (1 2), (13)(24) angle.r <= S_4.
$ 
Consider element $ 
sigma_1 = (1 2) (1 3) (2 4)  = ( 1 3 2 4) in H, \ 
sigma_2 = (1 2) in H.
$ 
We can check that any relation satisfied in $D_8$ by $r,s$ is also satisfiend in H by $sigma_1, sigma_2:$ 
$ 
sigma_1^4 = (1 3 2 4)^4 = e \ sigma_2^2  = (1 2 )^2 = e; \
sigma_2 sigma_1 = (1 2) (1 3 2 4) = (1 3) (2 4),\ 
sigma_1^(-1) sigma_2 = (1 4 2 3) (1 2) = (1 3) ( 2 4 ) = sigma_2 sigma_1\
$ 
we can see that relations satisfied by $r$ is also satisfied by $sigma_1,$ and relations satisfied by $s$ is also satisfied by $sigma_2.$ 

According to D&F 3rd ed. p38, a "useful fact" that was stated ( _without_ a proof) is: 

#quote(block:true)[
  If two groups $G = angle.l a_1, a_2, dots, a_n angle.r$ and $H = angle.l b_1, b_2, dots, b_n angle.r$ have the same relations among their generators $a_i$ and $b_i,$ then there is a unique homomorphism $phi : G -> H$ such that $phi(a_i) = b_i.$] Spcifically, in our case, there is a unique homomorphism $phi : D_8 -> H$ such that $phi(r) = sigma_1, phi(s) = sigma_2.$

Further, we check bijectivity by writing out all elements explicitely: $ 
e mapsto (1), s mapsto (1 2), r mapsto (1 3 2 4), \ 
s r mapsto (13) (24), s r^2  mapsto (3 4), s r^3 mapsto ( 1 4)(2 3);\
r^2  mapsto (12) (3 4),  r^3 mapsto (1 4 2 3)
$ 

$phi$ is bijective since all elements in $D_8$ have distinct images in $H.$ Thus, $phi$ is an isomorphism, and $H tilde.equiv D_8.$ 

#pagebreak()
= 3
#align(
  left,
  rect(inset: 8pt)[Show a proper subgroup of $QQ$ that is not cyclic.]
)
Consider the group $ 
S = {frac(a , 2^(k)) , a in ZZ, k in NN_0} .
$ 
$S <= Q$ since it is nonempty ($e in S$ ), closed under addition and inverses; explicitely, for $frac(a , 2^(k)) , frac(b , 2^(l)) in S,$
 $ frac(a , 2^(k)) + frac(b , 2^(l)) = frac(a 2^(l) + b 2^(k) , 2^(k+l)) in S, $and 
 $ -frac(a , 2^(k)) = frac(-a , 2^(k)) in S. $

Now, suppose $S = expectationvalue(q), q  = frac(a , 2^b) in S , $ so that $ S = expectationvalue(a/(2^b)) = {n a / b med | a,n in ZZ, b in NN_0} . o'$ Then consider $s = frac(1 , 2^(b+1)) in S,$ then $ 
1/(2^(b+1)) = n a/2^b => n a = 1/2
$ but this is impossible since $n a in ZZ.$ Thus, $S$ is not cyclic. 

Also, $S eq.not QQ$ since $1/3 in.not S.$ Thus, $S$ is a proper subgroup of $QQ$ that is not cyclic.

#pagebreak()
= 4 
#align(
  left,
  rect(inset: 8pt)[#image("assets/2025-10-17-20-44-04.png")]
)
We consider the sublattice of $D_(16):$ #image("assets/2025-10-17-20-50-02.png")

We can thus read off for the following parts:

a. $ angle.l s r^2 , r^4 angle.r , angle.l s r^6 angle.r , angle.l s r^2  angle.r , angle.l r^4 angle.r. $ 

b. $ 
D_(16), angle.l s angle.r , angle.l s,r^2  angle.r , angle.l s,r^4 angle.r  
$ 

#pagebreak()
= 5. 
#align(
  left,
  rect(inset: 8pt)[#image("assets/2025-10-17-20-57-34.png")]
)
=== 1. fiber of $phi.$
$ 
phi^(-1)(1) = {x| x in RR, x>0}, \ phi^(-1)(-1) = {x | x in RR, x<0}.
$ 


=== 2. Proof that $phi$ is a homomorphism.
Consider arbitrary $x,y in RR^*,$ we have $ 
phi(x y) = frac(x y , abs(x y)) = frac(x y , abs(x)abs(y)) = frac(x , abs(x)) frac(y , abs(y)) = phi(x) phi(y).   
$ 

#pagebreak()
= 6
#align(
  left,
  rect(inset: 8pt)[#image("assets/2025-10-17-21-02-59.png")]
)
- Homomorphism: consider arbitrary $(a,b), (c,d) in RR^2 .$ Then $ 
pi((a,b)+ (c,d)) & = pi(a+c, b+d) \ 
& =  a+c + b+ d \ 
& =  a+ b+ c+ d = pi(a,b)+ pi(c,d) 
$ 
- Surjective: for any $c in RR,$ we can find $(c,0) in RR^2 $ such that $pi(c,0) = c + 0 = c.$ Thus, $pi$ is surjective.

Geometrically, the kernel of $pi$ is $x + y = 0 => y = -x$, which is a line through the origin with slope -1 in the xy-plane.

The fibers of $pi$ are lines parallel to the kernel line, i.e. lines with slope -1. For example, the fiber $pi^(-1)(0)$ is the kernel line $y = -x,$ and the fiber $pi^(-1)(1)$ is the line $y = -x + 1,$etc. 

#pagebreak()
= 7
#align(
  left,
  rect(inset: 8pt)[#image("assets/2025-10-17-21-55-51.png")]
)

=== a. $H_1$is not normal. 
Counterexample: consider $ 
h_1 = display(mat(2,0;0,1)) in H, g_1 = display(mat(1,1;0,1)) in G, g_1^(-1)= display(mat(1,-1;0,1)) in G.
$ 
Then $ 
g_1 h_1 g_1^(-1) =  display(mat(1,1;0,1)) display(mat(2,0;0,1)) display(mat(1,-1;0,1)) = display(mat(2,-1;0,1)) in.not H
$ 
There's at least one element in the conjugate $g_1 H_1 g_1^(-1)$ that is not in $H_1.$
Thus, $H_1$ is not normal in $G.$

=== b. $H_2$ is normal.
Consider arbitrary $ 
h = display(mat(1,x;0,1)) , g= display(mat(a,b;0,1)) , g^(-1)= display(mat(1/a,-b/a;0,1)) quad (a eq.not 0). 
$ 
We compute the conjugate: $ 
g h g^(-1) = display(mat(a,b;0,1)) display(mat(1,x;0,1)) display(mat(1/a,-b/a;0,1)) = display(mat(1, a x; 0,1)) in H_2.  
$ 
Thus, for arbitrary $g in G, h in H_2,$ we have $g H_2 g^(-1) subset.eq H_2.$ Therefore, $H_2$ is normal in $G.$

Now let's describe the quotient group $G slash H_2.$ We construct a surjective map $phi: G -> K$ such that $ker(phi) = H_2$, and use the First Isomorphism Theorem to conclude $G slash H_2 tilde.equiv K.$
Since $a eq.not 0,$ consider the map $phi: G -> RR^times$ $ 
phi(mat(a,b;0,1)) = a .
$ 
We need to show that it's a surjective homomorphism with kernel $H_2.$
Consider arbitrary $ 
g_1 = display(mat(a_1, b_1;0,1)) , g_2 = display(mat(a_2, b_2;0,1)); quad  g_1g_2 = display(mat(a_1 a_2 , a_1 b_2 + b_1;0,1)) .
$ 
We have $ 
phi(g_1 g_2) = a_1 a_2;quad  phi(g_1)phi(g_2) = a 1 a_2 =  phi(g_1 g_2).
$ Thus $phi$ is a homomorphism.
For arbitrary $c in RR^times,$ we can find $g = display(mat(c,0;0,1)) in G$ such that $phi(g) = c.$ Thus, $phi$ is surjective.

The elements of the kernel of $phi$ is described as $ 
phi(mat(a,b;0,1)) = 1 =>quad a = 1 \ => quad ker(phi) = {mat(1,b;0,1) | b in RR} = H_2. 
$ 
By the First Isomorphism Theorem, we have $G slash H_2 tilde.equiv RR^times.$
