#set math.equation(numbering: "(1)")
#set text(
font: "Palatino Linotype",size: 11pt)
#set page(margin: (x: 1cm, y: 1cm), numbering: "1/1")
#import "@preview/physica:0.9.6": *
#place(top + right, rect(inset: 3pt)[math 541 hw8 | Harry Luo
])
= 1
#align(
  left,
  rect(inset: 8pt)[#image("assets/2025-11-06-19-30-22.png")]
)

From HW 7 we know that $S_n med (n >= 2)$ is generated by the transposition $(1 2)$ and the $n$-cycle $(1 2 ... n)$. Further, noticing $sigma: S_3 -> S_6$ is a homomorphism, we can find the image of these two generators to find the image of the whole group.

First, find the image $sigma(1 2)$ by considering its action on the set ${1, 2, 3, 4, 5, 6}$:$ 
(1 2) (1) &= (1 2) quad 1-> 2 \ (1 2) (1 2) &=1 quad 2-> 1\ 
(1 2) (2 3) &= (2 3 1) quad 3-> 5\ (1 2) (1 3) &=(1 3 2) quad 4 -> 6 \ 
(1 2) (2 1) &= (2 1 3) quad 5 -> 4 \ (1 2) (3) &= 3 quad 6 -> 3 $
Thus, we have $sigma(1 2) = (1 2)(3 5) (4 6)$.

Similarly, find the image $sigma(1 2 3)$ by considering its action on the set ${1, 2, 3, 4, 5, 6}$:$ 
(1 2 3) (1) &= (1 2 3) quad 1-> 5 \ (1 2 3) (1 2) &= (1 3) quad 2-> 4\ 
(1 2 3) (2 3) &= ( 1 2) quad 3-> 2 \ (1 2 3) (1 3) &= (2 3) quad 4 -> 3\ 
(1 2 3) (1 2 3) &= (1 3 2) quad 5-> 6 \ (1 2 3) ( 1 3 2 ) &= 1 quad 6 -> 1 $ 
Thus we have $sigma(1 2 3) = (1 5 6)( 2 4 3)$.

Then by homomorphism, $ 
sigma(2 3) = sigma((1 2)(1 2 3)) = sigma(12) compose sigma(1 3) =  (1 2)(3 5) (4 6)  (1 5 6)( 2 4 3) = (1 3) (2 6) (4 5)\ 
sigma(1 3) = sigma((12) (1 2 3)^2) = sigma(12) compose sigma(1 2 3)^2 = (1 2)(3 5) (4 6)  (1 6 5)( 2 3 4) = (1 4) (2 5) (3 6)\
sigma(1 3 2) = sigma((1 2 3)^2 ) =(1 6 5) (2 3 4)
$ 

#pagebreak()
= 2 
#align(
  left,
  rect(inset: 8pt)[#image("assets/2025-11-06-20-10-23.png")]
)

== a.
For each $g in G,$ consider its orbit under the action $pi(x):$$ 
cal(O)_g = { g , x g, x^2  g, dots, x^(n-1) g}. 
$ It's clear that $|cal(O)| = n$, since $x^n g = e g = g.$ We see that the action $pi(x)$ partitions $G$ into disjoint orbits of size $n$. Thus, $|G|$ is a multiple of $n$. Particularly, since $|G| = m n,$ there are $m$ such orbits. 

The permutation $pi(x)$ on each orbit acts as a cyclic shift. This means that the restriction of $pi(x)$ on $cal(O)_g$ is an n-cycle. Since there are m disjoint orbits, the permutation representation of $pi(x)$ is a product of $m$ disjoint $n$-cycles.   

== b
Recall from HW7 that an n-cycle can be written as n-1 transpositions. $pi(x)$ is therefore written as $m dot (n-1)$ transpositions.  Thus, in order for $pi(x)$ to be an odd permutation, $m$ and $n-1$ must be odd. This means that $n$ is even and $m$ is odd. In other words, $ 
n=|x| "is odd", quad m = |G|\/ |x| "is even" .
$ 
  
#pagebreak()
= 3
#align(
  left,
  rect(inset: 8pt)[#image("assets/2025-11-06-22-00-19.png")]
)
== a
Let
$
D_8 = angle.l r, s | r^4 = s^2 = 1, s r s = r^(-1) angle.r ,
quad
D_8 = {1, r, r^2, r^3, s, s r, s r^2, s r^3}.
$

We find the conjugacy classes by computing the conjugates of each element:

- $cal(O)_(1) = {1}$.
- $cal(O)_(r^2) = {r^2}$ since $r^2$ commutes with $r$ and $s$ (hence central).
- $cal(O)_(r) = {r, r^3}$ since $s r s^(-1) = r^(-1) = r^3$ and $r^k r r^(-k) = r$.
- $cal(O)_(s) = {s, s r^2}$ since $r s r^(-1) = s r^2$ and $r^2$ centralizes $s$.
- $cal(O)_(s r) = {s r, s r^3}$ (e.g., $s (s r) s^(-1) = s r^(-1) = s r^3$).
So collectively, the conjugacy classes are:
#box(
  $ 

  cal(O)_(1) &= {1}, & cal(O)_(r^2) &= {r^2}, & cal(O)_(r) &= {r, r^3}, \
  cal(O)_(s) &= {s, s r^2}, & cal(O)_(s r) &= {s r, s r^3}

  $
)

Size : $1 + 1 + 2 + 2 + 2 = 8 = |D_8|$.

== b 
This problem is made much simpler by a general property.
Let $(a, sigma)$ and $(b, tau)$ be two elements in $ZZ_2 times S_3.$ Their conjugate is given by:
$
(b, tau)(a, sigma)(b, tau)^(-1) = (b, tau)(a, sigma)(b^(-1), tau^(-1)) = (b + a - b, tau sigma tau^(-1)) = (a, tau sigma tau^(-1)),
$  where we used additive notation for $ZZ_2$ and the fact that it's abelian; and multiplicative notation for $S_3$. 
Therefore the conjugates of an element $(a, sigma)$ is ${a} times C_S_(3)(sigma)$. 

This implies that every elemnet in $ZZ_2$ is only conjugate to itself. Indeed, 
$C_ZZ_2(0) = {0}, C_ZZ_2(1) = {1}$

We now need to find conjugacy classes in $S_3.$ Start by listing all elements in $S_3:$
$
S_3 = { e, (1 2), (1 3), (2 3), (1 2 3), (1 3 2) }.
$
Recall from lecture that conjugacy classes in $S_3$ is grouped by cycle type. Thus we have: 

- Elements of $S_3$: $e, (12), (13), (23), (123), (132)$.
- Class of identity (type $1^3$): $cal(O)_(e) = {e}$.
- Class of transpositions (type $2,1$): $cal(O)_((12)) = {(12), (13), (23)}$.
- Class of 3-cycles (type $3$): $cal(O)_((123)) = {(123), (132)}$.

Collecting these results, 
$ 
cal(O)_((0,e)) &= {(0,e)}, "size"=1\
cal(O)_((0,(12))) &= {(0,(12)), (0,(13)), (0,(23))}, "size"=3 \
cal(O)_((0,(123))) &= {(0,(123)), (0,(132))}, "size"=2 \
cal(O)_((1,e)) &= {(1,e)}, "size"=1\ 
cal(O)_((1,(12))) &= {(1,(12)), (1,(13)), (1,(23))}, "size"=3\ 
cal(O)_((1,(123))) &= {(1,(123)), (1,(132))} "size"= 2
$

#pagebreak()
= 4 
#align(
  left,
  rect(inset: 8pt)[#image("assets/2025-11-07-12-56-37.png")]
)

== a. 
Since $G$ has at most 3 conjugacy classes, we write its class equation as $ 
|G| = n_1 + dots +  n_r, quad r <= 3,
$ where $n_i$ is the size of the $i$-th class. We analyze by cases on $r$:
- $r=1$.  Since there's only one conjugacy class, it must be the trivial class containing only the identity element. Thus $|G| = 1$.
- $r=2$. Write $|G| = 1 + n_2 => n_2 = |G| - 1.$ Since $n_2$ divides $|G|,$ we also have $|G| - 1 | |G| => |G| - 1 | 1 => |G| = 2.$
- $r = 3.$ Write $|G| = 1 + n_2 + n_3.$ Assume $1 <= n_2 <= n_3.$ We know that $n_2$ divides $|G|$, and $n_3 $ divides $|G|$ as well.  
  Since $n_3 < |G|$, we have $|G| >= 2 n_3$. Thus $ 
  |G| = 1 + n_2 + n_3 >= 2 n_3 quad => n_2 <= n_3 <= n_2 + 1. 
  $ 
  This implies that either $n_3 = n_2$ or $n_3 = n_2 + 1$.
  - If $n_3 = n_2$, then $|G| = 1 + 2 n_2$. Since $n_2 | |G|$, we have $2 n_2 | 1 + 2 n_2 => 2 n_2 | 1 => n_2 = 1.$ Thus $|G| = 3.$
  
  - If $n_3 = n_2 + 1$, then $|G| = 1 + n_2 + (n_2 + 1) = 2 n_2 + 2.$ Since $n_2 | |G|$, we have $n_2 | 2 (n_2 + 1) => n = 1$ or $2$. 
  
      If $n_2 = 1,$ then $|G| = 4.$ However this implies that $G$ is abelian and thus has 4 conjugacy classes, contradicting our assumption. So $n_2 = 2.$  Thus $|G| = 1 + 2 + 3= 6.$

Collecively, if $G$ has at most 3 conjugacy classes, then $|G| = 1, 2, 3, "or" 1 + 2 + 3,$

== b. 
We have shown in part a that, the forth option $|G| = 2+2 = 4,$ is impossible. 

For the first three options: 
- $|G|=1$, the trivial group, is unique. 
- $|G|=2$, whose only possibility is the cyclic group $ZZ_2,$ is unique.
- $|G|=3$, with the only possiblity being the cyclic group $ZZ_3,$ is unique.


== c. 
Let the classes be $cal(O)_e = {e}$, $cal(O)_g = {g, g'}$, and $cal(O)_h = {h, h', h''}$.

*Analyze the element $g$:* 

The size of its class is $|cal(O)_g| = 2$. 
The size of its centralizer is $|C_G  (g)| = |G| / |cal(O)_g| = 6 / 2 = 3$. 
Since $angle.l g angle.r subset.eq C_G  (g)$, the order of $g$ must divide 3. The order cannot be 1 (as $g != e$). Thus, the order of $g$ is 3. 
This implies $C_G  (g) = angle.l g angle.r = {1, g, g^2}$. The other element in the class, $g'$, must be $g^2 = g^(-1)$.

*Analyze the element $h$:* 

The size of its class is $|cal(O)_h| = 3$. 
The size of its centralizer is $|C_G (h)| = (|G|)/  (|cal(O)_h|) = 6 / 3 = 2$. 
This implies the order of $h$ is 2, and $C_G (h) = angle.l h angle.r = {1, h}$.

*Consider the conjugation $h g h^(-1)$:* 

This is the conjugate of $g$ by $h$. It must be an element in the class $cal(O)_g$. 
Could $h g h^(-1)  = g$? This would mean $h$ is in the centralizer of $g$, $C_G (g)$. But we found $C_G  (g) = {1, g, g^2}$ contains only elements of order 1 or 3, while $h$ has order 2. So $h g h^(-1) != g$. 
The only other element in $cal(O)_g$ is $g' = g^(-1)$. 
Therefore, we must have $h g h^(-1) = g^(-1)$.

*Conclusion:* 

We have found an element $g$ of order 3 and an element $h$ of order 2. These two elements generate $G$ (since no proper subgroup of a group of order 6 can contain elements of both order 2 and 3). 
They satisfy the relation $h g h^(-1) = g^(-1)$. 
This is precisely the presentation of the dihedral group $D_6$:
$
D_6 = angle.l r, s | r^3 = 1, s^2 = 1, s r s^(-1) = r^(-1) angle.r
$

The group $D_6$ is isomorphic to $S_3$ since it can be understood as permutations on the three tips of a tri-gon. Therefore, $G tilde.equiv  S_3$.





#pagebreak()
= 5
#align(
  left,
  rect(inset: 8pt)[#image("assets/2025-11-07-12-57-22.png")]
)

For any arbitrary $g_i in G,$ consider its centralizer $ 
C_G (g_i) = { x in G | x = g_i x g_i^(-1)} .
$ Since for each representative  $g_j$ we know that $g_j = g_i g_j g_i^(-1), g_j in C_G (g_i)$, for $1 <= j <= k.$ THerefore the size of the centralizer is at least $k,$ i.e., $|C_G (g_i)| >= k.$

Recall the class equation states that the order of the group is the sum of the sizes of its distinct conjugacy classes. Without loss of generality, let $g_1 = 1$ be the representative of the identity class, so $|cal(O)_(g_1)| = 1$.
Thus we have $ 
|G| = sum_(i=1)^m |cal(O)_(g_i)| = 1 + sum_(i=2)^m |cal(O)_(g_i)|. 
$ 

Meanwhile by the orbit-stabilizer theorem, we have $ 
|cal(O)_g| = |G : C_G (g_i)| = (|G|) / (|C_G (g_i)|) <= (|G|) / k
$ so that $ 
|G|  <= 1 + sum_(i=2)^m (|G|) / k = 1 + (m-1) (|G|) / k \ => |G| <= r.
$ By definition, $r$ is the number of distinct conjugacy classes that partition the group $G$. It is impossible for the number of subsets in a partition to be greater than the total number of elements. Thus, we must also have $r <= |G|$. 
Collectively, $ 
|G| = r. 
$ 
A group is abelian if and only if every element commutes with every other element. This is equivalent to the center of the group being the group itself, $Z(G) = G$. An element is in the center if and only if its conjugacy class has size 1. 

Therefore, since we have shown that the number of conjugacy classes is equal to the order of the group, every conjugacy class must have size 1.Thus $G$ is abelian.





#pagebreak()
= 6
#align(
  left,
  rect(inset: 8pt)[#image("assets/2025-11-07-12-57-38.png")]
)

Suppose for contradiction that for some non-idenetity element $x in G$, where $G$ is of odd order,  $x$ and $x^(-1)$ are conjugates. That is,   $ 
exists g in G med s.t. med g x g^(-1) = x^(-1) .
$ <eq.1>
Taking conjugate one more time, we see $ 
g^2  x g^(-2) = g x^(-1) g^(-1) = (g x g^(-1))^(-1) = (x^(-1))^(-1) = x  \ => g^2  x g^(-2) = x.
$ <eq.2>

Since $G$ is of odd order, $g^k = 1$ for some odd integer $k.$ Further, $gcd(2,k)=1$ so $ expectationvalue(g^2 )$ generates the same subgroup as $ expectationvalue(g)$. 
There exists an integer $m$ such that $2m = 1 mod k$. This implies:
$ g = g^1 = g^(2m) = (g^2)^m $
So, $g$ is a power of $g^2$.

From <eq.2>, we know that $g^2$ commutes with $x$. Since $g$ is a power of $g^2$, $g$ also commutes with $x$. Explicitly, $ 
g x g^(-1) = x. 
$ 
However this contradicts <eq.1>. Thus our assumption is false, and no non-identity element is conjugate to its inverse in a group of odd order. #h(1fr) $qed$