#import "@preview/physica:0.9.3": *
#import "@preview/ergo:0.2.0": *
#import "@preview/cetz:0.4.2": canvas, draw, tree
#import "@preview/wrap-it:0.1.1": wrap-content
#show: ergo-init.with(
    colors:     ergo-colors.bw,
    styles:     ergo-styles.sidebar1,
    breakable:  true,
    inline-qed: true,
    prob-nums:  false,
)


#show heading: text.with(size:1.5em ,weight: 1000)

#set text(11pt)
#set page(margin: (x: 2cm, y: 2cm),numbering: "1/1", columns: 1, flipped: false)
#set math.equation(numbering:"(1)")
#heading(numbering: none,outlined: false)[Notes on Abstract Algebra]
Harry Luo\

Lecture notes from Math 541 Modern Algebra I, Fall 2025. 

Rerference: 
- Dummit and Foote, Abstract Algebra, 3rd edition 
- lectures by prof. Mikhail Ivanov

#line(length: 100%, stroke: (thickness: 2pt))
#outline(indent: auto,depth:2)
#pagebreak()




= Chapter 1

#pagebreak()
= Chapter 2
== 2.1 


== 2.2

== 2.3
#heading(depth:1,numbering: none)[_Midterm 1 Cutoff_ ]
Midterm 2 coverage: 2.4, 2.5, 3.1, 3.2, 3.3, 3.5, 4.1, 4.2, 4.3, 4.4, 5.1, 5.2
== 2.4 _Subgroup generated by subsets of a group_
#line(length: 100% , stroke: 2pt) ///////////////////////////////
Given a group $G$ and a subset $A subset G$, we can construct the smallest subgroup of $G$ that contains $A$. This is called the *subgroup generated by $A$*. It's analogous to the span of a set of vectors in linear algebra, where we look for the smallest subspace containing a given set of vectors.

There are two equivalent ways to define the subgroup generated by a subset $A$ of a group $G$:

- *Top-down: an intersection of subgroups.*

  We can think of the subgroup generated by $A$ as the smallest subgroup of $G$ that contains $A$. _Smallest_ implies taking an intersection of all subgroups containing $A$.

  We first need to verify that the intersection of subgroups is indeed a subgroup.
 #prop[
    Let $cal(A)$ be a collection of subgroups of a group $G.$ The intesection $ inter.big_(H in cal(A)) H$ is also a subgroup of $G$. 
    ][    Identity is in every subgroup,so it's in the intersection.

    If $x, y$ in the intersection, then $x,y$ are in every subgroup in $cal(A)$. Since each subgroup is closed under the group operation, $x y^(-1)$ is in every subgroup, hence in the intersection.  #h(1fr) ]
  
  This proposition allows us to define the subgroup generated by $A$ as an intersection of subgroups.  
#defn[ Let $G$ be a group and $A subset G$ be a subset in G.The *subgroup generated by $G$ *, denoted $expval(A),$ is the intersection of all subgroups of $G$ that contain $A$.$ 
    expectationvalue(A) = inter.big_(H<= G \ A subset H) H.  
    $ 
    ]



- *Bottom-up: Words in Generators. *
  
  The first definition was clear but not constructive. We want to know what the elements of $expval(A)$ actually look like. We can describe an equivalent subgroup using "words" formed from elements of $A$ and their inverses.

  Notice that for a subgroup $H$ to contain $A$, it must be closed under group operation and taking inverses. This means $H$ must contain all elemenets in $A,$ all their inverses, and all finite products of these elements. This leads to the following definition: 

#defn[
    The subgroup generated by a subset $A subset G$, is the set of all finite products of elements of A and their inverses. $ 
    expectationvalue(A) = { a_1^e_1 a_2^e_2 ... a_n^e_n | n in ZZ^+, a_i in A, e_i = plus.minus 1  }. 
    $ 
    ]
  
After defining the subgroup generated by a subset $A$, we define a *Finitely generated group* as follows: 

#defn[
  A group $G$ is finitely generated if there exists a finite set $A$ such that $G = expval(A)$. 
  ]



  *_Example:_*
  1. $D_(2 n)= chevron.l r,s chevron.r $
  2. $Q_8 = chevron.l i, j chevron.r $
  3. $S_n:$
   - $S_1 = {e} = chevron.l e chevron.r , $ 
   - $S_2 = {e, (1 2)} = chevron.l (1 2) chevron.r , $
   - $S_n = chevron.l (1 med 2), (1 med 2 dots n) chevron.r $    
  4. $ "GL"_2 (RR) = chevron.l underbrace((mat(0,1;1,0)),"swap"), underbrace((mat(1,1;0,1)),"add"), underbrace((mat(a,0;0,1)),"multiply")    chevron.r $ 


== 2.5 _Lattice of subgroups of a Group_
#line(length: 100% , stroke: 2pt) ///////////////////////////////
We can draw a lattice diagram to visualize the structure of a group by showing its subgroups and their inclusion relationships.

The key idea is to find subgroups *generated by small subsets* (starting with single elements, then pairs or small combinations),and then arrange them by order and inclusion to form the partial order.

We will center this method around an example. 

Consider $D_8.$ Recalling the dihedral symmetry $s r^(-i) = r^(i) s$, we can write $ 
D_9 &= chevron.l r,s | r^4 = s^2 = e, s r s^(-1)= r^(-1) chevron.r  \ 
& = {e, r, r^2 , r^3, s, s r , s r^2 , s r^3 }.
$ 

We can categrozite them as subgroups generated by subsets of $D_8.$
- order 1: ${e} = chevron.l e chevron.r $
- order 2: $ 
  chevron.l r^2 chevron.r = {e, r^2}, quad
  chevron.l s chevron.r = {e, s}, quad
  chevron.l s r chevron.r = {e, s r}, quad
  chevron.l s r^2 chevron.r = {e, s r^2}, quad
  chevron.l s r^3 chevron.r = {e, s r^3}.
$ 
- order 4: $ 
 chevron.l r chevron.r = {e, r, r^2, r^3}, \
 chevron.l r^2 ,s chevron.r  = {e, r^2, s, s r^2}, \
 chevron.l r^2 , s r chevron.r = {e, r^2, s r, s r^3}.
$ In particular, notice that $ chevron.l r^2 ,s r^2 chevron.r = chevron.l r^2 ,s chevron.r ,$ and that $ chevron.l r^2 ,s r^3 chevron.r = chevron.l r^2 ,s r chevron.r ,$ so we only have 3 distinct subgroups of order 4. 
- order 8 is the whole group: $D_8 = chevron.l r,s chevron.r $

#figure(
    grid(
        columns: 2,     // 2 means 2 auto-sized columns
        gutter: 2mm,    // space between columns
        image("assets/2025-11-09-15-19-36.png", width: 60%),
         "Putting this all together, we can draw the lattice diagram of "+$D_8$+" seen on left."
    ))



#pagebreak()
= Chapter 3

== 3.1 _Quotient Groups_
#line(length: 100% , stroke: 2pt) ///////////////////////////////
=== The Big picture: homomorphisms and Fibers
Imagine a homomorphism $phi: G -> H.$ This map "collapses" $G$ onto $H$ by identifying certain elements of $G$ that map to the same element in $H$. The preimage of each element in $H$ under $phi$ is called a *fiber*. These fibers partition $G$ into disjoint subsets. 

For $X_a$ the fiber over $a in H,$ and $X_b$ the fiber over $b in H,$ define their product as the fiber over $a b$:
$ X_a X_b = X_(a b). $
This new operation on the fibers turns the set of fibers into a group, called a *quotient group*.

=== Kernel and Cosets 
The most important fiber is that over the identity element $e_H$ in $H$. 
#defn[Kernel][
  If $phi: G -> H$ is a homomorphism, the *kernel* of $phi$ is the set of elements in $G$ that map to the identity $e_H$  in $H$: $ 
  ker(phi) = {g in G| phi(g) = e_H }. 
  $ 
]
The kernel is a subgroup of $G$, and it has a special structure as follows 
#prop[Let $phi: G-> H$ be a homomorphism. Then 

1. $phi(e_G) = phi(e_H).$
2. $phi(g^(-1)) = phi(g)^(-1) med forall g in G.$
3. $ker(phi) <= G.$
4. The image $im(phi)$ is a subgroup of $H.$  
  ][] 

Next, we define *cosets*, which are understood as neighboring copies of a subgroup within the larger group.

#defn[Coset][ For any subgroup $N <= G,$ and any element $g in G,$ the set $ 
g N = {g n | n in N} 
$ is called a *left coset* of $N$ in $G$. The element $g$ is called a *representative* of the coset $g N$. Similarly, $N g = {n g| n in N}$ is a right coset. 
  ]

A crucial link between fibers, kernels and cosets is established by the following proposition:

#prop[Let $phi: G -> H$ be a homomorphism and $K = ker(phi)$ be its kernel. Let $X$ be the fiber of $a in H$. For any $u in X$ (i.e. $phi(u)=a$ ), then
$X = u K = {u k| k in K}$ is a left coset of Kernel.     ][]

=== Normal Subgroups and Quotient Groups

The fibers of a homomorphism partition the group into cosets of the Kernel. The group of these cosets forms the *quotient group*.

#defn[Operation on Cosets][
  Let $K = ker(phi)$. The set of fibers is denoted by  $G slash K$. We define a kinary operation on $G slash K$ as follows: $ 
  (u K)(v K) = (u v) K, quad forall u K, v K in G slash K. 
  $ 
   
]
In the particular case where this operation is well-defined, i.e. for a different $u' , v', $ we still have $(u' v') K = (u v)K,$ we say that $K$ is a *normal subgroup* of $G$. 
#defn[Normal subgroup][
  a Subgroup $N$ of a group $G$ is called a *normal subgroup* if $forall g in G,$ and $n in N,$$ 
  g n g^(-1) in N quad <=> g N g^(-1) = N.
  $ Denote  this $N$  as $N lt.tri.eq G.$ The elements $g n g^(-1)$ is the *conjugate* of $n$ by $g$. 
      
]
It's clear that onjugating a normal subgroup by any element of the group leaves the subgroup unchanged.

It can be proven that a normal subgroup has several equivalent characterizations:
#theorem[Let $N <= G.$ The following are equivalent: $ 
1.& N lt.tri.eq G. \
2. &forall g in G, g N = N g.\ 
3. & (u n) (v m) N= (u v) N quad forall u,v in G, "and" forall n,m in N. \
4. & N = ker(phi) "for some homomorphism" phi.
$<thm.normal_subgroup> 
 ][]
This theorem is the cornerstone of the section. It tells us that the subgroups we can "quotient by" are precisely the normal subgroups, which are precisely the kernels of homomorphisms.

If $N lt.tri.eq G$, the set of left cosets of $N$ in $G$, denoted $G\/N$, forms a group under the operation $(u N)( v N) = (u v)N$.
A quotient group is then defined as follows

#defn[
Quotient Group][
  Let $N lt.tri.eq G$ be a normal subgroup. The *quotient group* $G slash N$ is the set of left cosets of $N$ in $G$ with the operation defined by $ 
  (u N)(v N) = (u v) N, quad forall u , v  in G . 
  $Its set-builder representation is thus $ 
  G slash N = { g N | g in G }
  $ 
  
]





== 3.2 _Cosets and Lagrange Theorem_
#line(length: 100% , stroke: 2pt) ///////////////////////////////
This section builds on homomorphisms and normal subgroups (Section 3.1) to explore cosets of a subgroup $H <= G$. Cosets provide a way to "slice" $G$ into equal-sized pieces, leading to powerful counting results. The main tool is Lagrange's Theorem, which relates subgroup orders to the group's order.

=== Cosets Partition the Group.
Recall, for any subgroup $H <= G$ and any element $g in G,$ the set $g H = {g h | h in H}$ is called a *left coset* of $H$ in $G$. These form a partition of $G.$

#prop[Let $G $ be a group and $H <= G$. THen there exists distinct elements $g_1, g_2, dots, g_k in G$ for some finite $k,$ such that: 
1. $ G = union.big_i g_i H $ (Cosets partition G, and their union covers G.)
2. $ g_i H inter g_j H = emptyset ,(i eq.not j) $  
3. $ |g H| = |H| forall g in G. $    ][]

Core Insight: Cosets are "translates" of $H$ that tile $G$ without overlap. The number $k$ of cosets is called the index of $H$ in $G$.


#defn[
  Index of a subgroup][
    The index of $H <= G$, denoted $|G:H|$. is the number of distinct left cosets of $H$ in $G$. ( the "size" of the quotient group).
    
    For finite $G, $ $ 
    |G:H| = frac(|G|,|H|). 
    $ 
         
]

Lagrange theorem then follows naturally from the properties of cosets:
#thm[Lagrange's Theorem :

  Let $G$ be a finite group and $H <= G$. Then $|H|$ divides $|G|$, i.e., $|G| = |H| dot |G : H|$.
][]

=== Main Corollaries
Lagrange's Theorem has immediate consequences for elements, small groups, and normality.

#cor("Order of an element divides group order.")[If $G$ is finite and $g in G,$ then $|g|$ divides $|G.$  ][Let $H<= G$ and $H = angle.l g angle.r $. Then $|H| = |g|$. By Lagrange, $|H|$ divides $|G|$, so $|g|$ divides $|G|.$       ]

#cor("Groups of prime order are cyclic.")[If $|G| = p$ is prime, then $G$ is cyclic, i.e., $G tilde.equiv Z_p$ ][ The subgroups are only ${e}$ (order 1) and $G$ itself (order $p$ ) both divides $p.$ Let $g in G \\{e}, angle.l g angle.r <= G, $ then by Lagrange theorem, $|g|$ divides $p,$ so $|g| = p.$ Thus $G = angle.l g angle.r tilde.eq Z_p $ is cyclic.       ]

#cor("Subgroups of index 2 are normal.")[If $H <= G$ with $|G:H| = 2,$ then $H lt.tri.eq G.$ ][ There are only two left cosets: $H$ and $g H$ for some $g in G \\ H.$ And only two right cosets $H, H g$. Since both left cosets and right cosets partition $G,$ they must match, i.e. $g H = H g (forall g in G.)$ Therefore by @thm.normal_subgroup, $H lt.tri.eq G$       ]



== 3.3 _The Isomorphism Theorems_
#line(length: 100% , stroke: 2pt) ///////////////////////////////
The Isomorphism Theorems formalize the relationship between homomorphisms, kernels, and quotient groups established in Sec 3.1. 

For purpose of exam, we focus on the First Isomorphism Theorem, while understanding the 3rd theorem statement. The 2nd and 4th are omitted (they are so hard!)

=== The First Isomorphism Theorem
The First isomorphism theorem states that if we map $G$ to $H$ via a homomorphism $phi$, then the image of $phi$ is isomorphic to the quotient of $G$ by the kernel of $phi$.  




== 3.5
#pagebreak()
= Chapter 4

== 4.1

== 4.2
_Groups acting on themselves by left multiplication -- *Cayley's Theorem*_

- Le

== 4.3

== 4.4

#pagebreak()
= Chapter 5

== 5.1

== 5.2


#heading(numbering: none)[_Mitterm 2 Cutoff_]




