#import "@preview/physica:0.9.3": *
#import "@preview/ergo:0.2.0": *
#import "@preview/ilm:1.4.1": *
#import "@preview/wrap-it:0.1.1": wrap-content
#show: ergo-init.with(
    colors:     ergo-colors.bootstrap,
    styles:     ergo-styles.sidebar2,
    breakable:  true,
    inline-qed: true,
    prob-nums:  false,
)
#set math.equation(numbering:"(1)")
#heading(depth:1,numbering: none)[_Midterm 1 Cutoff_ ]
Midterm 2 coverage: 2.4, 2.5, 3.1, 3.2, 3.3, 3.5, 4.1, 4.2, 4.3, 5.1, 5.2
== 2.4 _Subgroup generated by subsets of a group_
#line(length: 100% , stroke: 2pt) ///////////////////////////////
Given a group $G$ and a subset $A subset G$, we can construct the smallest subgroup of $G$ that contains $A$. This is called the *subgroup generated by $A$*. It's analogous to the span of a set of vectors in linear algebra, where we look for the smallest subspace containing a given set of vectors.

There are two equivalent ways to define the subgroup generated by a subset $A$ of a group $G$:

- *Top-down: an intersection of subgroups.*

  We can think of the subgroup generated by $A$ as the smallest subgroup of $G$ that contains $A$. _Smallest_ implies taking an intersection of all subgroups containing $A$.

  We first need to verify that the intersection of subgroups is indeed a subgroup.
 #prop[
    Let $cal(A)$ be a collection of subgroups of a group $G.$ The intesection $ inter.big_(H in cal(A)) H$ is also a subgroup of $G$. 
    ][    Identity is in every subgroup,so it's in the intersection.

    If $x, y$ in the intersection, then $x,y$ are in every subgroup in $cal(A)$. Since each subgroup is closed under the group operation, $x y^(-1)$ is in every subgroup, hence in the intersection.  #h(1fr) ]
  
  This proposition allows us to define the subgroup generated by $A$ as an intersection of subgroups.  
  #defn[ Let $G$ be a group and $A subset G$ be a subset in G.The *subgroup generated by $G$ *, denoted $expval(A),$ is the intersection of all subgroups of $G$ that contain $A$.$ 
    expectationvalue(A) = inter.big_(H<= G \ A subset H) H.  
    $ 
    ]



- *Bottom-up: Words in Generators. *
  
  The first definition was clear but not constructive. We want to know what the elements of $expval(A)$ actually look like. We can describe an equivalent subgroup using "words" formed from elements of $A$ and their inverses.

  Notice that for a subgroup $H$ to contain $A$, it must be closed under group operation and taking inverses. This means $H$ must contain all elemenets in $A,$ all their inverses, and all finite products of these elements. This leads to the following definition: 

  #defn[
    The subgroup generated by a subset $A subset G$, is the set of all finite products of elements of A and their inverses. $ 
    expectationvalue(A) = { a_1^e_1 a_2^e_2 ... a_n^e_n | n in ZZ^+, a_i in A, e_i = plus.minus 1  }. 
    $ 
    ]
  
After defining the subgroup generated by a subset $A$, we define a *Finitely generated group* as follows: 
  #defn[
  A group $G$ is finitely generated if there exists a finite set $A$ such that $G = expval(A)$. 
  ]



#example[
  1. $D_(2 n)= chevron.l r,s chevron.r $
  2. $Q_8 = chevron.l i, j chevron.r $
  3. $S_n:$
   - $S_1 = {e} = chevron.l e chevron.r , $ 
   - $S_2 = {e, (1 2)} = chevron.l (1 2) chevron.r , $
   - $S_n = chevron.l (1 med 2), (1 med 2 dots n) chevron.r $    
  4. $ "GL"_2 (RR) = chevron.l underbrace((mat(0,1;1,0)),"swap"), underbrace((mat(1,1;0,1)),"add"), underbrace((mat(a,0;0,1)),"multiply")    chevron.r $ 
   ]


== 2.5 _Lattice of subgroups of a Group_
#line(length: 100% , stroke: 2pt) ///////////////////////////////
We can draw a lattice diagram to visualize the structure of a group by showing its subgroups and their inclusion relationships.

The key idea is to find subgroups *generated by small subsets* (starting with single elements, then pairs or small combinations),and then arrange them by order and inclusion to form the partial order.

We will center this method around an example. 

Consider $D_8.$ Recalling the dihedral symmetry $s r^(-i) = r^(i) s$, we can write $ 
D_9 &= chevron.l r,s | r^4 = s^2 = e, s r s^(-1)= r^(-1) chevron.r  \ 
& = {e, r, r^2 , r^3, s, s r , s r^2 , s r^3 }.
$ 

We can categrozite them as subgroups generated by subsets of $D_8.$
- order 1: ${e} = chevron.l e chevron.r $
- order 2: $ 
  chevron.l r^2 chevron.r = {e, r^2}, quad
  chevron.l s chevron.r = {e, s}, quad
  chevron.l s r chevron.r = {e, s r}, quad
  chevron.l s r^2 chevron.r = {e, s r^2}, quad
  chevron.l s r^3 chevron.r = {e, s r^3}.
$ 
- order 4: $ 
 chevron.l r chevron.r = {e, r, r^2, r^3}, \
 chevron.l r^2 ,s chevron.r  = {e, r^2, s, s r^2}, \
 chevron.l r^2 , s r chevron.r = {e, r^2, s r, s r^3}.
$ In particular, notice that $ chevron.l r^2 ,s r^2 chevron.r = chevron.l r^2 ,s chevron.r ,$ and that $ chevron.l r^2 ,s r^3 chevron.r = chevron.l r^2 ,s r chevron.r ,$ so we only have 3 distinct subgroups of order 4. 
- order 8 is the whole group: $ D_8 = chevron.l r,s chevron.r $

Putting this all together, we can draw the lattice diagram of $D_8$seen below.

#figure(image("assets/2025-11-09-15-19-36.png", width: 60%), caption: "lattice of " +$D_8.$ )

#pagebreak()
= Chapter 3

== 3.1 _Quotient Groups_
#line(length: 100% , stroke: 2pt) ///////////////////////////////
=== The Big picture: homomorphisms and Fibers
Imagine a homomorphism $phi: G -> H.$ This map "collapses" $G$ onto $H$ by identifying certain elements of $G$ that map to the same element in $H$. The preimage of each element in $H$ under $phi$ is called a *fiber*. These fibers partition $G$ into disjoint subsets. 

For $X_a$ the fiber over $a in H,$ and $X_b$ the fiber over $b in H,$ define their product as the fiber over $a b$:
$ X_a X_b = X_(a b). $
This new operation on the fibers turns the set of fibers into a group, called a *quotient group*.

=== Kernel and Cosets 
The most important fiber is that over the identity element $e_H$ in $H$. 
#defn[Kernel][
  If $phi: G -> H$ is a homomorphism, the *kernel* of $phi$ is the set of elements in $G$ that map to the identity $e_H$  in $H$: $ 
  ker(phi) = {g in G| phi(g) = e_H }. 
  $ 
]
The kernel is a subgroup of $G$, and it has a special structure as follows 
#prop[Let $phi: G-> H$ be a homomorphism. Then 

1. $phi(e_G) = phi(e_H).$
2. $phi(g^(-1)) = phi(g)^(-1) med forall g in G.$
3. $ker(phi) <= G.$
4. The image $im(phi)$ is a subgroup of $H.$  
  ][] 

Next, we define *cosets*, which are understood as neighboring copies of a subgroup within the larger group.

#defn[Coset][ For any subgroup $N <= G,$ and any element $g in G,$ the set $ 
g N = {g n | n in N} 
$ is called a *left coset* of $N$ in $G$. The element $g$ is called a *representative* of the coset $g N$. Similarly, $N g = {n g| n in N}$ is a right coset. 
  ]

A crucial link between fibers, kernels and cosets is established by the following proposition:

#prop[Let $phi: G -> H$ be a homomorphism and $K = ker(phi)$ be its kernel. Let $X$ be the fiber of $a in H$. For any $u in X$ (i.e. $phi(u)=a$ ), then
$X = u K = {u k| k in K}$ is a left coset of Kernel.     ][]

=== Normal Subgroups and Quotient Groups

The fibers of a homomorphism partition the group into cosets of the Kernel. The group of these cosets forms the *quotient group*.

#defn[Operation on Cosets][
  Let $K = ker(phi)$. The set of fibers is denoted by  $G slash K$. We define a kinary operation on $G slash K$ as follows: $ 
  (u K)(v K) = (u v) K, quad forall u K, v K in G slash K. 
  $ 
   
]
In the particular case where this operation is well-defined, i.e. for a different $u' in u K , v' in v K, $ we still have $(u' v') K = (u v)K,$ we say that $K$ is a *normal subgroup* of $G$. 
#defn[Normal subgroup][
  a Subgroup $N$ of a group $G$ is called a *normal subgroup* if $forall g in G,$ and $n in N,$$ 
  g n g^(-1) in N quad <=> g N g^(-1) = N.
  $ Denote  this $N$  as $N lt.tri.eq G.$ The elements $g n g^(-1)$ is the *conjugate* of $n$ by $g$. 
      
]
It's clear that onjugating a normal subgroup by any element of the group leaves the subgroup unchanged.

It can be proven that a normal subgroup has several equivalent characterizations:
#theorem[Let $N <= G.$ The following are equivalent: $ 
1.& N lt.tri.eq G. \
2. &forall g in G, g N = N g.\ 
3. & (u n) (v m) N= (u v) N quad forall u,v in G, "and" forall n,m in N. \
4. & N = ker(phi) "for some homomorphism" phi.
$<thm.normal_subgroup> 
 ][]
This theorem is the cornerstone of the section. It tells us that the subgroups we can "quotient by" are precisely the normal subgroups, which are precisely the kernels of homomorphisms.

If $N lt.tri.eq G$, the set of left cosets of $N$ in $G$, denoted $G\/N$, forms a group under the operation $(u N)( v N) = (u v)N$.
A quotient group is then defined as follows

#defn[
Quotient Group][
  Let $N lt.tri.eq G$ be a normal subgroup. The *quotient group* $G slash N$ is the set of left cosets of $N$ in $G$ with the operation defined by $ 
  (u N)(v N) = (u v) N, quad forall u , v  in G . 
  $Its set-builder representation is thus $ 
  G slash N = { g N | g in G }
  $ 
  
]

In the quotient group, each element is a coset, and the group is "zoomed out" with respect to a normal subgroup. The group operation is defined by $a N dot b N = a b med N$, and the identity is $e_G N = N$.

This section can be thus summarized as:

#blockquote[If $N lt.tri.eq G,$ then $G slash N = {g N | g in G}$ with operation $a N dot b N = a b med N.$   ]



== 3.2 _Cosets and Lagrange Theorem_
#line(length: 100% , stroke: 2pt) ///////////////////////////////
This section builds on homomorphisms and normal subgroups (Section 3.1) to explore cosets of a subgroup $H <= G$. Cosets provide a way to "slice" $G$ into equal-sized pieces, leading to powerful counting results. The main tool is Lagrange's Theorem, which relates subgroup orders to the group's order.

=== Cosets Partition the Group.
Recall, for any subgroup $H <= G$ and any element $g in G,$ the set $g H = {g h | h in H}$ is called a *left coset* of $H$ in $G$. These form a partition of $G.$

#prop[Let $G $ be a group and $H <= G$. THen there exists distinct elements $g_1, g_2, dots, g_k in G$ for some finite $k,$ such that: 
1. $ G = union.big_i g_i H $ (Cosets partition G, and their union covers G.)
2. $ g_i H inter g_j H = emptyset ,(i eq.not j) $  
3. $ |g H| = |H| forall g in G. $    ][]

Core Insight: Cosets are "translates" of $H$ that tile $G$ without overlap. The number $k$ of cosets is called the index of $H$ in $G$.


#defn[
  Index of a subgroup][
    The index of $H <= G$, denoted $|G:H|$. is the number of distinct left cosets of $H$ in $G$. ( the "size" of the quotient group).
    
    For finite $G, $ $ 
    |G:H| = frac(|G|,|H|). 
    $ 
         
]

Lagrange theorem then follows naturally from the properties of cosets:
#thm("Lagrange's Theorem" )[
  Let $G$ be a finite group and $H <= G$. Then $|H|$ divides $|G|$, i.e., $ |G| = |H| dot |G : H| . $
][]

=== Main Corollaries
Lagrange's Theorem has immediate consequences for elements, small groups, and normality.

#cor("Order of an element divides group order.")[If $G$ is finite and $g in G,$ then $|g|$ divides $|G.$  ][Let $H<= G$ and $H = angle.l g angle.r $. Then $|H| = |g|$. By Lagrange, $|H|$ divides $|G|$, so $|g|$ divides $|G|.$       ]

#cor("Groups of prime order are cyclic.")[If $|G| = p$ is prime, then $G$ is cyclic, i.e., $G tilde.equiv Z_p$ ][ The subgroups are only ${e}$ (order 1) and $G$ itself (order $p$ ) both divides $p.$ Let $g in G \\{e}, angle.l g angle.r <= G, $ then by Lagrange theorem, $|g|$ divides $p,$ so $|g| = p.$ Thus $G = angle.l g angle.r tilde.eq Z_p $ is cyclic.       ]

#cor("Subgroups of index 2 are normal.")[If $H <= G$ with $|G:H| = 2,$ then $H lt.tri.eq G.$ ][ There are only two left cosets: $H$ and $g H$ for some $g in G \\ H.$ And only two right cosets $H, H g$. Since both left cosets and right cosets partition $G,$ they must match, i.e. $g H = H g (forall g in G.)$ Therefore by @thm.normal_subgroup, $H lt.tri.eq G$       ]



== 3.3 _The Isomorphism Theorems_
#line(length: 100% , stroke: 2pt) ///////////////////////////////
The Isomorphism Theorems formalize the relationship between homomorphisms, kernels, and quotient groups established in Sec 3.1. 

For purpose of exam, we focus on the First Isomorphism Theorem, while understanding the 3rd theorem statement. The proof to 1st and 3rd are omitted; The 2nd and 4th are omitted (they are so hard!)

=== The First Isomorphism Theorem
The First isomorphism theorem states that if we map $G$ to $H$ via a homomorphism $phi$, then the image of $phi$ is isomorphic to the quotient of $G$ by the kernel of $phi$.  

#thm("First Isomorphism Theorem")[
Let $phi: G-> H$ be a homomorphism, then $ker(phi) lt.tri.eq G $ and  $ 
G slash ker(phi) tilde.eq Im(phi). 
$ 
][]

There are several important corollaties to this theorem: 
#cor(1)[$phi$ is injective iff $ker(phi) = {e_G}.$ ][ If $ker(phi) = e_G$, then $G slash ker(phi) = G tilde.eq Im(phi) $ so $phi$ is bijective. Conversely, if $phi$ is injective, then $|ker(phi)| = 1,$ so $ker(phi) = {e_G}.$ ]

#cor(2)[ If $G$ finite, then $|G:ker(phi)| = |Im(phi)|$ . ][ By Lagrange theorem, $|G:ker(phi)| = |G| slash |ker(phi)|.$ By First Isomorphism theorem, $|G slash ker(phi)| = |Im(phi)|.$  ]

#cor(3)[If $phi$ is surjective ( $Im(phi) = H),$ then $G slash ker(phi) tilde.eq H.$  ][Trivial.]

#cor(4)[If $phi$ is injective, then $G tilde.eq Im(phi).$ ][Trivial.]

=== The Third Isomorphism Theorem
 The Third Isomorphism Theorem deals with nested quotients. It can be memorized as "invert and cancel" as one would do with fractions.
#thm("Third Isomorphism Theorem")[
Let $G$ be a group, and let $H lt.tri.eq G, K lt.tri.eq G, H <= K.$ Then $K slash H lt.tri.eq G slash K,$ and $ 
G slash H slash.big K slash H tilde.eq G slash K.  
$ 
][]

== 3.5 _Transpositions and the Alternating Group_
#line(length: 100% , stroke: 2pt) ///////////////////////////////

We establish a fundamental property of permutations: each one has a "parity" (even or odd). Thi sidea is formalized by constructing a homomorphism from $S_n$ to ${plus.minus 1}$. The kernel of this map, the set of even permutations, is the *Alternating Group $A_n.$ *  

=== Transpositions as Genrator of $S_n.$

Recall a permutation can be written as a product of cycles (not nessessarily disjoint) in many non-unique ways.

#defn[Transposition][A Transposition is a 2-cycle $(i j)$. ]

Every permutation can be beilt from transpositions. In fact: 
#prop[The symmetric group $S_n$ is generated by transpositions. $ 
S_n= angle.l (i j) | 1<= i <= j <= n angle.r  
$ 
][Since evvery permutation can be written as product of disjoint cycles, it suffices to show that eveyr cycle can be written as a product of transpositions. Indeed, for any $k$- cycle, $ 
(a_1 a_2 dots a_k) = (a_1 a_k)(a_1 a_(k-1)) dots (a_1 a_2).
$]

Note that this decomposition is not unique. For example, $(1  2  3) = (1  3)(1  2)$ but also $(1  2  3) = (2  1)(2  3)$. However, the parity of the number of transpositions is an invariant, as we will now prove.

=== The `sign` homomorphism. 

To formalize the idea of parity, we construct a homomorphism from $S_n$ to the multiplicative group ${plus.minus 1}$.

To construct, recall that $S_n$ acts on $P[x_1,x_2, dots, x_n]$ s.t. $ 
sigma dot P[x_1,x_2,dots,x_n]= P[x_(sigma(1)), x_(sigma(2)), dots, x_(sigma(n))   ]. 
$ 
Consider polynomial in $n$ variables $ 
Delta_n equiv product_(1 <= i <= j <= n) (x_i - x_j). 
$ 
For example, $ 
Delta_4 = (x_1-x_2)(x_1-x_3)(x_1 - x_4)(x_2-x_3)(x_2-x_4)(x_3-x_4), \ 
(1 2) Delta_4 =  (x_2-x_1)(x_2-x_3)(x_2 - x_4)(x_1-x_3)(x_1-x_4)(x_3-x_4) = - Delta_4; \ 
(1 2 3) Delta_4 = (x_2-x_3)(x_2-x_1)(x_2 - x_4)(x_3-x_1)(x_3-x_4)(x_1-x_4), =  Delta_4.
$ 

#defn[The sign function][Using $Delta_n$, define sign as  $ 
"sign" (sigma)= frac(sigma(Delta_n) ,Delta_n) = plus.minus 1.
$ A permutation $sigma$ is called even if $"sign"(sigma) = +1$ , and odd if $"sign"(sigma) = -1$.
]

#theorem[Sign homomorphism][The sign map is a surjective homomorphism from $S_n$ to ${plus.minus 1}.$ That is, $ 
"sign"(tau sigma) = "sign"(tau)"sign"(sigma). 
$ ][$ "sign"(tau) "sign"(sigma) = frac((tau sigma)  Delta_n , Delta_n)= frac(tau (sigma(Delta_n)) , Delta_n) frac(sigma(Delta_n) ,Delta_n ) = "sign"(tau)"sign"(sigma).  $ 
Proof for surjectivity is omitted.]

=== The alternating group $A_n.$
For even permutation $sigma$ , $"sign"(sigma)= 1.$ We exploit this to define the alternating group.
#defn[Alternating group $A_n$ ][$ 
A_n = ker("sign") 
$ is the subgroup of $S_n$ consisting of even permutations   ]

Since $A_n$ is the kernel of a homomorphism, it's a normal subgroup of $S_n.$ Thus by first isomorphism theorem, $ 
S_n slash A_n tilde.eq Im("sign") = {plus.minus 1} .
$ 
This immediately tells us the index and order of $A_n.$$ 
|S_n : A_n|= frac(|S_n| , |A_n|) = |Im("sign")| = 2 quad => quad |A_n| = (|S_n|)/2 =  frac(n!,2).
$ There are only two cosets of $A_n$, the even permutations ( $A_n$ itself) and the odd permutations ( $ (1 2) A_n$ ). In other words, $ 
sigma in A_n: "even"  \ sigma in S_n - A_n: "odd". 
$ 

Therefore, the transposition $(i j)$ is odd. 
- Even permutation = prod. of even number of transpositions.
- Odd permutation = prod. of odd number of transpositions.
equivalently, $ 
(a_1 a_2 dots a_k) = cases("odd" quad k "even", "even" quad k "odd".) 
$ 

#example[Consider the following permutation$ 
display(mat(1,2,3,4,5,6,7,8,9; 2,4,6,1,5,9,3,7,8))  \ 
= (1 2 4)(3 6 9 8 7) (5)= (1 2)(24)(36)(69)(98)(87) 
$ There are even number (6) of transpositions, so it's an even permutation.
]
=== Alternative Characterization of sign.

The sign of a permutation can also be determined by counting the number of times a larger number precedes a smaller number in the image of the permutation.
#defn[Inversion][
Spcifically, consider the permutation $ 
sigma = display(mat(1,2,dots, dots, n; a_1,a_2  dots, a_i,a_j,dots a_n))  
$ 
For each $a_i> a_j, (i < j),$ inversion happens once. $"sign"(sigma) = $ parity of number of inversions.]

#example[consider the lower line of permutation to be $ 
2,4,6,1,5,9,3,7,8. 
$ Fix 2, found 1 preceeding element bigger that 2, inversion +1. Fix 4, found 2 preceeding elements bigger than 4, inversion +2. Repeat the process for all elements, we find 10 inversions. So it's a even permutation.]

 

#pagebreak()
= Chapter 4

// Midterm 2 coverage: 2.4, 2.5, 3.1, 3.2, 3.3, 3.5, 4.1, 4.2, 4.3, 5.1, 5.2

== 4.1 _Group actions_
#line(length: 100% , stroke: 2pt) ///////////////////////////////
Summary: 
Group action is a particular mapping. It studies groups via their effect on sets. The orbit-stabilizer theorem quantifies this relationship, showing that the size of an orbit is measured by how large the stabilizer is. Transitive actions are those where the group moves any element to any other, representing maximal symmetry.
#figure(image("assets/2025-11-11-09-08-58.png"),caption:"Visualizing group actions, orbits, and stabilizers." )

=== Basic Definitions 
Let $G$ be a group and $A$ a nonempty set. We define many things about how $G$ can "act" on $A$ via a mapping that respects the group structure. 
#defn[Group Action][
  A *left group action* of $G$ on $A$ is a map $G times A -> A,$ with $(g,a) mapsto g dot a,$ satisfying
  1. _associativity:_ $d_1 dot (g_2 dot a) = (g_1 g_2) dot a$ for all $g_1, g_2 in G$ and $a in A.$
  2. _identity:_ $e dot a = a$ for all $a in A.$
   
When such an action exists, we say that $G$ *acts on* $A.$   
]

#defn[Permutation Representation][
  For each fixed $g in G,$ define the map $sigma_g: A -> A$ by $sigma_g (a) = g dot a.$ The axioms above ensure that $sigma_g$ is a permutation of $A.$ The map $ 
  phi: G-> S_A, quad phi(g) = sigma_g 
  $ is a homomorphism, called the *permutation representation* associated to the action of $G$ on $A.$ 
  
]

#defn[Kernel of the action][ The kernel of theaction is the set of elements that act trivially on _every_ element of $A$. $ 
ker = {g in G| g dot a = a quad forall a in A.} 
$ This coicides with the kernel of the permutation representation $phi.$
 ]


#defn[Faithful Action][The action is *faithful* if its kernel is trivial. That is, only the identity element of $G$ acts trivially on all elements of $A$. Equivalently, the permutation representation $phi$ is injective.  ]

=== Orbits and stabilizers. 
For a fixed element $a in A,$
#defn[Orbit][ The *orbit* of $a$ under the action of $G$ is the set $ 
cal(O)_a = {g dot a | g in G} quad subset.eq A. 
$ It's the set of elements in $A$ that can be reached from $a$ via the action of $G.$
]

#prop[Orbits are equivalence classes][
  Define a relation $~$ on $A$ by $a~ b "iff" b = g dot a$   for some $g in G.$ Then
   $~$ is an equivalence relation on $A.$ (reflexive, symmetric, transitive). Thus:
  - The equivalence class of $a$ (the set of all $b$ s.t. the relation holds )  is the orbit $cal(O)_a.$
  - Equivalence classes $=>$orbits _partition_ $A$ into disjoint subsets.  
][]

#defn[Stabilizer][ The *stabilizer* of $a$ in $G$ is the subgroup $ 
G_a = {g in G | g dot a = a} quad <= G. 
$ It's the set of elements in $G$ that leave $a$ fixed under the action. 
]
=== Orbit-Stabilizer Theorem
Since the stabilizer $G_a$ is a subgroup of $G$, we can consider the set of left cosets $G slash G_a$ (note that it's _not_ a quotient group in genral). Each coset corresponds to a distinct destination for $a$, so $|G slash G_a|$ counts the elements in the orbit. By Lagrange's Theorem:
$ |G| = |G_a| dot |G slash G_a|. $

There is a bijection $g G_a mapsto g dot a$ between $G slash G_a$ and $cal(O)_a$, so the size of orbit equals size of cosets of stabilizer, giving:
#thm("Orbit-Stabilizer Theorem")[
  Let $G$ be a finite group acting on a set $A.$ For any $a in A,$ 
  $ |cal(O)_a| = |G : G_a| = frac(|G|, |G_a|) quad <=> quad |G| = |cal(O)_a| dot |G_a|.
  $ 
][]

=== Transitive Actions 

#defn[Transitive Action][
The action of $G$ on $A$ is* transitive* if there is only one orbit, i.e., for any $a, b in A$, there exists $g in G$ such that $b = g dot a$.]
Equivalently, the action is transitive if and only if $|cal(O)_a| = |A|$ for some (hence every) $a in A$. By the Orbit-Stabilizer Theorem, this means $|A| = |G : G_a|$ for any $a in A$.
  

 



== 4.2 _Groups acting on themselves by left multiplication -- *Cayley's Theorem*_
#line(length: 100% , stroke: 2pt) ///////////////////////////////
#defn[Left regular action][
- Let $G$ be a group. The  *left regular action* of $G$ on itself is defined by $ 
g dot a = g a quad forall g, a in G. 
$ 
where $g a$ is the product in the group $G.$] 

#prop[The left regular action is 
- faithful. The kernel is trivial.
- transitive. THere is only one orbit; for any $a, b in G,$ exists $g in G$ s.t. $b = g a.$
][]

=== Cayley's theorem
#theorem[Cayley's theorem][Every group $G$ is isomorphic to a subgroup of the symmetric group $S_G.$ If $|G|=n$ , then $G$ is isomorphic to a subgroup of $S_n.$ ][]

*Remark.* The theorem shows that the abstract notion of a group is equivalent to the historical notion of a permutation group. However, studying groups as subgroups of $S_n$ is often computationally impractical since $S_n$ is much larger than $G$.

== 4.3 _Groups acting on themselves by Conjugation -- Class Equation_

=== The Class Equation

Another action of a group on itself is via conjugation. 
#definition[Conjugation Action][
  A group $G$ acts on itself by *conjugation* via the map $ 
  g dot a = g a g^(-1) quad forall g, a in G
  $
]

For the conjugation action, we identify the following structures:


- *Orbit*: The orbit of $a in G$ is its conjugacy class $ 
{g a g^(-1) | g in G} 
$ 
- *Stabilizer:* The stabilizer of $a$ is its centralizer $ 
C_G (a) = {g in G | g a = a g}. 
$ 
- *Kernel:* The set of elements that act trivially on all of $G$ is precisely the center $ 
Z(G) = {g in G | g x = x g quad forall x in G} 
$ 
Since the conjugacy classes partition $G,$ let $g_1, g_2, dots, g_k$ be representatives of the non-central classes. By the orbit-stabilizer theorem, we have the *class equation* as follows. 
#theorem[Class Equation][
  Let $G$ be a finite group. Then 
  $ 
  |G| = |Z(G)| + sum_(i=1)^k |G : C_G (g_i)|. 
  $ 
][]




#pagebreak()
= Chapter 5

== 5.1

== 5.2
